spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.135.121:3306/j2eeproj?useSSL=false
    username: root
    password: rootroot
    thymeleaf:
       cache: false
       mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.group2.project.entity